apiVersion: v1
kind: Service
metadata:
  name: hello-tbs
  labels:
    app.kubernetes.io/name: hello-tbs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-tbs
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tbs
  labels:
    app.kubernetes.io/name: hello-tbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-tbs
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-tbs
    spec:
      containers:
      - image: harbor.haas-231.pez.pivotal.io/demo-apps/hello-tbs-music:latest
        name: hello-tbs
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
~
